image: python:3.9.5-alpine

pipelines:
  pull-requests:
    '**':
      - step:
          script:
            - apk add --no-cache --update build-base postgresql-dev postgresql-libs
            - export VIRTUAL_ENV=${PWD}
            - python3 -m venv $VIRTUAL_ENV
            - export PATH="$VIRTUAL_ENV/bin:$PATH"
            - pip install -r requirements.txt
            - cd server
            - pip install -e .
            - pytest -v
definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: antibodydb_test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
