image: python:3.9.5-alpine

pipelines:
  pull-requests:
    '**':
      - step:
          script:
            - apk add --no-cache --update build-base postgresql-client postgresql-dev postgresql-libs
            - echo "127.0.0.1 db" > /etc/hosts
            - PGPASSWORD=password psql -h db -d antibodydb_test -U postgres -f deploy/postgresql_init_scripts/create_tables.sql
            - export VIRTUAL_ENV=${PWD}
            - python3 -m venv $VIRTUAL_ENV
            - export PATH="$VIRTUAL_ENV/bin:$PATH"
            - python3 -m pip install --upgrade pip
            - pip install -r requirements-dev.txt
            - cd server
            - pip install -e .
            - pytest -v
          services:
            - ingestmock
            - postgres
            - uuidmock
definitions:
  services:
    ingestmock:
      image: mockserver/mockserver
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: antibodydb_test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    uuidmock:
      image: mockserver/mockserver
