version: '3'

services:
  db:
    environment:
      - POSTGRES_DB=antibodydb
      - POSTGRES_PASSWORD=password
    image: postgres:13.3
    ports:
      - '5432:5432'
    volumes:
      - ./deploy/postgresql_init_scripts:/docker-entrypoint-initdb.d
  mockserver:
    command: -serverPort 80
    image: mockserver/mockserver
    networks:
      default:
        aliases:
          - ingestmock
          - uuidmock
  uuidserver:
    build:
      context: .
      dockerfile: DockerfileUUIDServer
    command: "ruby /app/uuid.rb"
    networks:
      default:
        aliases:
          - ingestserver
    volumes:
      - ./uuidserver:/app
  web:
    build:
      args:
        - DEVELOPMENT=1
      context: .
      dockerfile: DockerfileDev
    depends_on:
      - db
      - mockserver
      - uuidserver
    environment:
        - FLASK_APP=antibodyapi
        - FLASK_ENV=development
