version: "3.7"

services:
  antibody-api:
    hostname: antibody-api
    container_name: antibody-api
    # Use the published image from DockerHub instead of local build
    # Exit with an error message containing err if ANTIBODY_API_VERSION is unset or empty in the environment
    image: hubmap/antibody-api:${ANTIBODY_API_VERSION:?err}
    environment:
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    init: true
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://hubmap-auth:8888" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gateway_hubmap
    ports:
      - '5000:5000'
    volumes:
      # Flask configuration
      - "./instance:/app/var/antibodyapi-instance"
      # uWSGI log
      - "./server/log:/app/server/log"

networks:
  gateway_hubmap:
    external: true
