version: '3'

services:
  web:
    container_name: antibody-api
    environment:
        - HOST_GID=${HOST_GID:-1000}
        - HOST_UID=${HOST_UID:-1000}
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://hubmap-auth:3333" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: antibody-api
    image: antibody-api:${ANTIBODY_API_VERSION:?err}
    init: true
    networks:
      - gateway_hubmap
    ports:
      - '5000:5000'
    restart: always
    volumes:
      - ./instance:/app/var/antibodyapi-instance

networks:
  gateway_hubmap:
    external: true
